--Comandos criados para exercício interno durante treinamento na Lydians em 2024.

--SELECT sequence_name FROM user_sequences WHERE sequence_name = 'SEQCODFUNCIONARIO'
--DROP SEQUENCE SEQCOD;

DROP TABLE SUPFUNCIONARIO
DROP SEQUENCE SEQCODFUNCIONARIO
CREATE TABLE SUPFUNCIONARIO (
  SEQCODFUNCIONARIO NUMBER(20) NOT NULL,
  MATRICULA INTEGER NOT NULL,
  NOME VARCHAR(150) NOT NULL,
  DTNASC DATE NOT NULL,
  CONSTRAINT PK_SUPFUNCIONARIO PRIMARY KEY (SEQCODFUNCIONARIO)
);
CREATE SEQUENCE SEQCODFUNCIONARIO MINVALUE 1 START WITH 1 INCREMENT BY 1;
SELECT * FROM SUPFUNCIONARIO

DROP TABLE SUPDESCRICAO
DROP SEQUENCE SEQCODDESCRICAO
CREATE TABLE SUPDESCRICAO (
  SEQCODDESCRICAO NUMBER(20) NOT NULL,
  DESCRICAO VARCHAR(150) NOT NULL,
  CONSTRAINT PK_SUPDESCRICAO PRIMARY KEY (SEQCODDESCRICAO)
);
CREATE SEQUENCE SEQCODDESCRICAO MINVALUE 1 START WITH 1 INCREMENT BY 1;
SELECT * FROM SUPDESCRICAO ORDER BY SEQCODDESCRICAO


DROP TABLE SUPMALOTE
DROP SEQUENCE SEQCODMALOTE
-- Criar tabela SUPMALOTE
CREATE TABLE SUPMALOTE (
  SEQCODMALOTE NUMBER(20) NOT NULL,
  CODFUNCIONARIO NUMBER(20) NOT NULL,
  DTENVIO DATE NOT NULL,
  DTCONFERENCIA DATE NOT NULL,
  SITUACAOMALOTE VARCHAR(150) NOT NULL,
  CODDESCRICAO NUMBER(20) NOT NULL,
  CONSTRAINT PK_SUPMALOTE_SEQCODMALOTE PRIMARY KEY (SEQCODMALOTE),
  CONSTRAINT FK_SUPMALOTE_CODFUNCIONARIO FOREIGN KEY (CODFUNCIONARIO) REFERENCES SUPFUNCIONARIO (SEQCODFUNCIONARIO),
  CONSTRAINT FK_SUPMALOTE_CODDESCRICAO FOREIGN KEY (CODDESCRICAO) REFERENCES SUPDESCRICAO (SEQCODDESCRICAO)
);
CREATE SEQUENCE SEQCODMALOTE MINVALUE 1 START WITH 1 INCREMENT BY 1;
