--ITEM 1--
UPDATE SUPFUNCIONARIO
SET NOME = REPLACE((REPLACE((REPLACE((REPLACE((REPLACE(NOME,'$','')), '&','')),'_','')),'@','')),'>','');

--ITEM 3--
UPDATE SUPMALOTE
SET DTENVIO = '01/09/2021'
WHERE DTENVIO IS NULL;

UPDATE SUPMALOTE
SET DTCONFERENCIA = To_Date('DDMMYYYY') +41
WHERE DTCONFERENCIA IS NULL;

UPDATE SUPMALOTE
SET CODDESCRICAO = 5, SITUACAOMALOTE = 'Situação desconhecida.'
WHERE CODDESCRICAO IS NULL;

--ITEM 4--
INSERT INTO SUPFUNCIONARIO (SEQCODFUNCIONARIO, MATRICULA, NOME, DTNASC)
VALUES (SEQCODFUNCIONARIO.NEXTVAL FROM CORFUNCIONARIOS), 24, 'Sofia Ionescu-Ogrezeanu', '14/04/1902');

INSERT INTO SUPFUNCIONARIO (SEQCODFUNCIONARIO, MATRICULA, NOME, DTNASC)
VALUES (SEQCODFUNCIONARIO.NEXTVAL FROM CORFUNCIONARIOS), 278, 'Valentina Tereshkova', '30/12/1922');

SELECT * FROM SUPFUNCIONARIO;

--ITEM 5--
INSERT INTO SUPDESCRICAO (SEQCODDESCRICAO, DESCRICAO)
VALUES (SEQCODDESCRICAO.NEXTVAL, 'Bloqueado pela justiça'), (SEQCODDESCRICAO.NEXTVAL, 'Malote sem os dados do destinatário')

SELECT * FROM SUPDESCRICAO;