--Comandos criados para exercício interno durante treinamento na Lydians em 2024.

DROP SEQUENCE SEQ_CAPHOTELCLIENTEFRIGOBAR;
DROP TABLE CAPHOTELCLIENTEFRIGOBAR;

DROP SEQUENCE SEQ_CAPHOTELFRIGOBAR;
DROP TABLE CAPHOTELFRIGOBAR;

DROP SEQUENCE SEQ_CAPHOTELCLIENTEQUARTO;
DROP TABLE CAPHOTELCLIENTEQUARTO;

DROP SEQUENCE SEQ_CAPHOTELCLIENTE;
DROP TABLE CAPHOTELCLIENTE;

DROP SEQUENCE SEQ_CAPHOTELQUARTO;
DROP TABLE CAPHOTELQUARTO;

'--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  HOTEL QUARTO
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
CREATE SEQUENCE SEQ_CAPHOTELQUARTO MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE TABLE CAPHOTELQUARTO (
  SEQCODQUARTO NUMBER(10) NOT NULL,
  NOMEQUARTO VARCHAR(150) NULL,
  DESCRICAOQUARTO VARCHAR (255) NULL,
  VLRQUARTODIARIA NUMBER(10, 2) NULL
);

ALTER TABLE CAPHOTELQUARTO ADD CONSTRAINT PK_CAPHOTELQUARTO PRIMARY KEY (SEQCODQUARTO);
INSERT INTO CAPHOTELQUARTO (SEQCODQUARTO, NOMEQUARTO, DESCRICAOQUARTO, VLRQUARTODIARIA) VALUES (SEQ_CAPHOTELQUARTO.NEXTVAL, 'CASAL', 'QUARTO COM CAMA DE CASAL E FRIGOBAR', 250);
INSERT INTO CAPHOTELQUARTO (SEQCODQUARTO, NOMEQUARTO, DESCRICAOQUARTO, VLRQUARTODIARIA) VALUES (SEQ_CAPHOTELQUARTO.NEXTVAL, 'SOLTEIRO', 'QUARTO COM CAMA DE SOLTEIRO E FRIGOBAR', 150);

'--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  HOTEL CLIENTE
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
CREATE SEQUENCE SEQ_CAPHOTELCLIENTE MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE TABLE CAPHOTELCLIENTE (
  SEQCODCLIENTE NUMBER(10) NOT NULL,
  NOME VARCHAR(150) NULL,
  DOCCLIENTE NUMBER(10) UNIQUE NOT NULL
 );
ALTER TABLE CAPHOTELCLIENTE ADD CONSTRAINT PK_CAPHOTELCLIENTE_SEQCOD PRIMARY KEY (SEQCODCLIENTE);

INSERT INTO CAPHOTELCLIENTE (SEQCODCLIENTE, NOME, DOCCLIENTE) VALUES (SEQ_CAPHOTELCLIENTE.NEXTVAL, 'BRAYAN COIMBRA', 7070707070);
INSERT INTO CAPHOTELCLIENTE (SEQCODCLIENTE, NOME, DOCCLIENTE) VALUES (SEQ_CAPHOTELCLIENTE.NEXTVAL, 'JOÃO DE DEUS', 6060606060);
INSERT INTO CAPHOTELCLIENTE (SEQCODCLIENTE, NOME, DOCCLIENTE) VALUES (SEQ_CAPHOTELCLIENTE.NEXTVAL, 'WELLINGTON PUYOL', 5050505050);
INSERT INTO CAPHOTELCLIENTE (SEQCODCLIENTE, NOME, DOCCLIENTE) VALUES (SEQ_CAPHOTELCLIENTE.NEXTVAL, 'RODRIGOL DA SILVA', 4040404040);

'--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  HOTEL CLIENTE - QUARTO
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
CREATE SEQUENCE SEQ_CAPHOTELCLIENTEQUARTO MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE TABLE CAPHOTELCLIENTEQUARTO(
  SEQCODCLIENTEQUARTO NUMBER (20) NOT NULL,
  CLIENTE INTEGER NOT NULL,
--  IDHOSPEDAGEM INTEGER NOT NULL,
  CHECKIN DATE NULL,
  CHECKOUT DATE NULL,
  QTDDIARIA NUMBER(3) NULL,
  TPQUARTOCONTRATADO INTEGER NOT NULL,
  DEBITOTOTAL NUMBER(10,2) NULL
);
ALTER TABLE CAPHOTELCLIENTEQUARTO ADD CONSTRAINT PK_CAPHOTELCLIENTEQUARTO PRIMARY KEY (SEQCODCLIENTEQUARTO);
ALTER TABLE CAPHOTELCLIENTEQUARTO ADD CONSTRAINT FK_CAPHOTELCLIENTEQUARTO_DOC FOREIGN KEY (CLIENTE) REFERENCES CAPHOTELCLIENTE (SEQCODCLIENTE);
ALTER TABLE CAPHOTELCLIENTEQUARTO ADD CONSTRAINT FK_CAPHOTELCLQT_QUARTO FOREIGN KEY (TPQUARTOCONTRATADO) REFERENCES CAPHOTELQUARTO (SEQCODQUARTO);

INSERT INTO CAPHOTELCLIENTEQUARTO (SEQCODCLIENTEQUARTO, CLIENTE, CHECKIN, CHECKOUT, QTDDIARIA, TPQUARTOCONTRATADO, DEBITOTOTAL)
VALUES (SEQ_CAPHOTELCLIENTEQUARTO.NEXTVAL, 1, To_Date('20240410', 'YYYYMMDD'), To_Date('20240417', 'YYYYMMDD'), 8, 1, 2000);

INSERT INTO CAPHOTELCLIENTEQUARTO (SEQCODCLIENTEQUARTO, CLIENTE, CHECKIN, CHECKOUT, QTDDIARIA, TPQUARTOCONTRATADO, DEBITOTOTAL)
VALUES (SEQ_CAPHOTELCLIENTEQUARTO.NEXTVAL, 2, To_Date('20240411', 'YYYYMMDD'), To_Date('20240417', 'YYYYMMDD'), 8, 1, 2000);

INSERT INTO CAPHOTELCLIENTEQUARTO (SEQCODCLIENTEQUARTO, CLIENTE, CHECKIN, CHECKOUT, QTDDIARIA, TPQUARTOCONTRATADO, DEBITOTOTAL)
VALUES (SEQ_CAPHOTELCLIENTEQUARTO.NEXTVAL, 3, To_Date('20240412', 'YYYYMMDD'), To_Date('20240417', 'YYYYMMDD'), 8, 2, 2000);

INSERT INTO CAPHOTELCLIENTEQUARTO (SEQCODCLIENTEQUARTO, CLIENTE, CHECKIN, CHECKOUT, QTDDIARIA, TPQUARTOCONTRATADO, DEBITOTOTAL)
VALUES (SEQ_CAPHOTELCLIENTEQUARTO.NEXTVAL, 4, To_Date('20240413', 'YYYYMMDD'), To_Date('20240417', 'YYYYMMDD'), 8, 2, 2000);

INSERT INTO CAPHOTELCLIENTEQUARTO (SEQCODCLIENTEQUARTO, CLIENTE, CHECKIN, CHECKOUT, QTDDIARIA, TPQUARTOCONTRATADO, DEBITOTOTAL)
VALUES (SEQ_CAPHOTELCLIENTEQUARTO.NEXTVAL, 1, To_Date('20240420', 'YYYYMMDD'), To_Date('20240427', 'YYYYMMDD'), 9, 2, 2250);

INSERT INTO CAPHOTELCLIENTEQUARTO (SEQCODCLIENTEQUARTO, CLIENTE, CHECKIN, CHECKOUT, QTDDIARIA, TPQUARTOCONTRATADO, DEBITOTOTAL)
VALUES (SEQ_CAPHOTELCLIENTEQUARTO.NEXTVAL, 3, To_Date('20240424', 'YYYYMMDD'), To_Date('20240430', 'YYYYMMDD'), '9', 1, 2250);

'--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  HOTEL FRIGOBAR
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
CREATE SEQUENCE SEQ_CAPHOTELFRIGOBAR MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE TABLE CAPHOTELFRIGOBAR (
  SEQCODPRODUTO NUMBER (20) NOT NULL,
  NOMEPRODUTO VARCHAR (255) NULL,
  VALORPRODUTO NUMBER(3,2)  NULL
);
ALTER TABLE CAPHOTELFRIGOBAR ADD CONSTRAINT PK_CAPHOTELFRIGOBAR PRIMARY KEY (SEQCODPRODUTO);

INSERT INTO CAPHOTELFRIGOBAR (SEQCODPRODUTO, NOMEPRODUTO, VALORPRODUTO) VALUES (SEQ_CAPHOTELFRIGOBAR.NEXTVAL, 'COCA COLA', 5);
INSERT INTO CAPHOTELFRIGOBAR (SEQCODPRODUTO, NOMEPRODUTO, VALORPRODUTO) VALUES (SEQ_CAPHOTELFRIGOBAR.NEXTVAL, 'AGUA COM GÁS', 2.50);
INSERT INTO CAPHOTELFRIGOBAR (SEQCODPRODUTO, NOMEPRODUTO, VALORPRODUTO) VALUES (SEQ_CAPHOTELFRIGOBAR.NEXTVAL, 'ALFAFA COM CEBOLA', 2.50);
INSERT INTO CAPHOTELFRIGOBAR (SEQCODPRODUTO, NOMEPRODUTO, VALORPRODUTO) VALUES (SEQ_CAPHOTELFRIGOBAR.NEXTVAL, 'PASTEL DE VENTO', 5);
INSERT INTO CAPHOTELFRIGOBAR (SEQCODPRODUTO, NOMEPRODUTO, VALORPRODUTO) VALUES (SEQ_CAPHOTELFRIGOBAR.NEXTVAL, 'PASTEL DE CARNE DE CAVALO', 5.60);
INSERT INTO CAPHOTELFRIGOBAR (SEQCODPRODUTO, NOMEPRODUTO, VALORPRODUTO) VALUES (SEQ_CAPHOTELFRIGOBAR.NEXTVAL, 'PASTEL DE PICANHA', 9);
INSERT INTO CAPHOTELFRIGOBAR (SEQCODPRODUTO, NOMEPRODUTO, VALORPRODUTO) VALUES (SEQ_CAPHOTELFRIGOBAR.NEXTVAL, 'STROGONOFF DE MAMINHA', 6.50)

'--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  HOTEL CLIENTE - FRIGOBAR
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
CREATE SEQUENCE SEQ_CAPHOTELCLIENTEFRIGOBAR MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE TABLE CAPHOTELCLIENTEFRIGOBAR (
  SEQCODCLIENTEFRIGOBAR NUMBER (20) NOT NULL,
  CLIENTE INTEGER NOT NULL,
  PRODUTO INTEGER NOT NULL,
  QTDCONSUMIDA INTEGER NULL,
  IDHOSPEDAGEM INTEGER NOT NULL
);
ALTER TABLE CAPHOTELCLIENTEFRIGOBAR ADD CONSTRAINT PK_CAPHOTELCLIENTEFRIGOBAR PRIMARY KEY (SEQCODCLIENTEFRIGOBAR);
ALTER TABLE CAPHOTELCLIENTEFRIGOBAR ADD CONSTRAINT FK_HT_CLIENTE_FRIGO FOREIGN KEY (CLIENTE) REFERENCES CAPHOTELCLIENTE (SEQCODCLIENTE);
ALTER TABLE CAPHOTELCLIENTEFRIGOBAR ADD CONSTRAINT FK_HT_CLIENTE_FRIGOBAR FOREIGN KEY (PRODUTO) REFERENCES CAPHOTELFRIGOBAR (SEQCODPRODUTO);
ALTER TABLE CAPHOTELCLIENTEFRIGOBAR ADD CONSTRAINT FK_HT_CLIENTE_HOSPEDAGEM FOREIGN KEY (IDHOSPEDAGEM) REFERENCES CAPHOTELCLIENTEQUARTO (SEQCODCLIENTEQUARTO);

INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 1, 1, 2, 1);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 1, 2, 3, 1);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 1, 3, 4, 1);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 1, 4, 5, 1);

INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 1, 1, 2, 5);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 1, 2, 3, 5);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 1, 3, 4, 5);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 1, 14, 5, 5);


INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 2, 1, 4, 2);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 2, 2, 5, 2);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 2, 4, 7, 2);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 2, 3, 9, 2);

INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 3, 1, 4, 3);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 3, 2, 8, 3);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 3, 4, 4, 3);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 3, 3, 5, 3);

INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 4, 1, 4, 4);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 4, 2, 6, 4);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 4, 4, 8, 4);
INSERT INTO CAPHOTELCLIENTEFRIGOBAR (SEQCODCLIENTEFRIGOBAR, CLIENTE, PRODUTO, QTDCONSUMIDA, IDHOSPEDAGEM) VALUES (SEQ_CAPHOTELCLIENTEFRIGOBAR.NEXTVAL, 4, 3, 1, 4);

--PRODUTOS CONSUMIDOS POR CLIENTE CONFORME A HOSPEDAGEM
SELECT  CAPHOTELCLIENTEQUARTO.SEQCODCLIENTEQUARTO AS IDHOSP,
        CAPHOTELCLIENTE.SEQCODCLIENTE AS IDCLIENTE,
        CAPHOTELFRIGOBAR.NOMEPRODUTO AS ProdutoConsumido,
        CAPHOTELFRIGOBAR.VALORPRODUTO AS ValorUnitarioProduto,
        CAPHOTELCLIENTEFRIGOBAR.QTDCONSUMIDA AS QtdConsumidaProduto,
        CAPHOTELCLIENTEFRIGOBAR.QTDCONSUMIDA * CAPHOTELFRIGOBAR.VALORPRODUTO AS DebitoProduto,
        CAPHOTELCLIENTEQUARTO.DEBITOTOTAL AS DebitoHospedagemMaisProduto
FROM CAPHOTELCLIENTEFRIGOBAR
JOIN CAPHOTELCLIENTE ON CAPHOTELCLIENTE.SEQCODCLIENTE = CAPHOTELCLIENTEFRIGOBAR.CLIENTE
JOIN CAPHOTELFRIGOBAR ON CAPHOTELFRIGOBAR.SEQCODPRODUTO = CAPHOTELCLIENTEFRIGOBAR.PRODUTO
JOIN CAPHOTELCLIENTEQUARTO ON CAPHOTELCLIENTEQUARTO.SEQCODCLIENTEQUARTO = CAPHOTELCLIENTEFRIGOBAR.IDHOSPEDAGEM
JOIN CAPHOTELQUARTO ON CAPHOTELQUARTO.SEQCODQUARTO = CAPHOTELCLIENTEQUARTO.TPQUARTOCONTRATADO
WHERE CAPHOTELCLIENTE.SEQCODCLIENTE = 1 AND CAPHOTELCLIENTEQUARTO.SEQCODCLIENTEQUARTO = 5

--PRODUTOS CONSUMIDOS POR CLIENTE CONFORME A HOSPEDAGEM FILTRADA POR DATA DE CHECK IN
SELECT  CAPHOTELCLIENTE.SEQCODCLIENTE AS IDCLIENTE,
        CAPHOTELCLIENTE.NOME AS NomeCliente,
        CAPHOTELCLIENTEQUARTO.CHECKIN AS CheckIn,
        CAPHOTELCLIENTEQUARTO.CHECKOUT AS CheckOut,
        CAPHOTELCLIENTEQUARTO.QTDDIARIA AS QtdDiaria,
        CAPHOTELQUARTO.NOMEQUARTO AS Quarto,
        CAPHOTELFRIGOBAR.NOMEPRODUTO AS ProdutoConsumido,
        CAPHOTELFRIGOBAR.VALORPRODUTO AS ValorUnitarioProduto,
        CAPHOTELCLIENTEFRIGOBAR.QTDCONSUMIDA AS QtdConsumidaProduto,
        CAPHOTELCLIENTEFRIGOBAR.QTDCONSUMIDA * CAPHOTELFRIGOBAR.VALORPRODUTO AS DebitoProduto,
        CAPHOTELCLIENTEQUARTO.DEBITOTOTAL AS DebitoHospedagemMaisProduto
FROM CAPHOTELCLIENTEFRIGOBAR
JOIN CAPHOTELCLIENTE ON CAPHOTELCLIENTE.SEQCODCLIENTE = CAPHOTELCLIENTEFRIGOBAR.CLIENTE
JOIN CAPHOTELFRIGOBAR ON CAPHOTELFRIGOBAR.SEQCODPRODUTO = CAPHOTELCLIENTEFRIGOBAR.PRODUTO
JOIN CAPHOTELCLIENTEQUARTO ON CAPHOTELCLIENTEQUARTO.SEQCODCLIENTEQUARTO = CAPHOTELCLIENTEFRIGOBAR.IDHOSPEDAGEM
JOIN CAPHOTELQUARTO ON CAPHOTELQUARTO.SEQCODQUARTO = CAPHOTELCLIENTEQUARTO.TPQUARTOCONTRATADO
WHERE CHECKIN BETWEEN '10/04/2024' AND '11/04/2024'
AND CAPHOTELCLIENTE.SEQCODCLIENTE = 1

--VERIFICA QUANTIDADE DE HOSPEDAGENS
SELECT  CAPHOTELCLIENTE.SEQCODCLIENTE AS IDCLIENTE,
        CAPHOTELCLIENTE.NOME AS NomeCliente,
        CAPHOTELCLIENTEQUARTO.CHECKIN AS CheckIn,
        CAPHOTELCLIENTEQUARTO.CHECKOUT AS CheckOut,
        CAPHOTELCLIENTEQUARTO.QTDDIARIA AS QtdDiaria,
        CAPHOTELQUARTO.NOMEQUARTO AS Quarto
FROM CAPHOTELCLIENTEFRIGOBAR
JOIN CAPHOTELCLIENTE ON CAPHOTELCLIENTE.SEQCODCLIENTE = CAPHOTELCLIENTEFRIGOBAR.CLIENTE
JOIN CAPHOTELFRIGOBAR ON CAPHOTELFRIGOBAR.SEQCODPRODUTO = CAPHOTELCLIENTEFRIGOBAR.PRODUTO
JOIN CAPHOTELCLIENTEQUARTO ON CAPHOTELCLIENTEQUARTO.SEQCODCLIENTEQUARTO = CAPHOTELCLIENTEFRIGOBAR.IDHOSPEDAGEM
JOIN CAPHOTELQUARTO ON CAPHOTELQUARTO.SEQCODQUARTO = CAPHOTELCLIENTEQUARTO.TPQUARTOCONTRATADO
WHERE CHECKIN BETWEEN '10/04/2024' AND '22/04/2024' AND CAPHOTELCLIENTE.SEQCODCLIENTE = 1
GROUP BY
    CAPHOTELCLIENTE.SEQCODCLIENTE,
    CAPHOTELCLIENTE.NOME,
    CAPHOTELCLIENTEQUARTO.CHECKIN,
    CAPHOTELCLIENTEQUARTO.CHECKOUT,
    CAPHOTELCLIENTEQUARTO.QTDDIARIA,
    CAPHOTELQUARTO.NOMEQUARTO;

SELECT  CAPHOTELCLIENTEQUARTO.SEQCODCLIENTEQUARTO AS IDHOSP,
        CAPHOTELCLIENTE.DOCCLIENTE AS DocCliente,
        CAPHOTELCLIENTE.SEQCODCLIENTE AS CodCliente,
        CAPHOTELCLIENTE.NOME, CAPHOTELCLIENTEQUARTO.CHECKIN AS CheckIn,
        CAPHOTELCLIENTEQUARTO.CHECKOUT AS CheckOut,
        CAPHOTELCLIENTEQUARTO.TPQUARTOCONTRATADO AS TpQuarto,
        CAPHOTELQUARTO.NOMEQUARTO AS NomeQuarto,
        CAPHOTELQUARTO.DESCRICAOQUARTO AS DescricaoQuarto,
        CAPHOTELCLIENTEQUARTO.QTDDIARIA AS QtdDiaria,
        CAPHOTELCLIENTEQUARTO.DEBITOTOTAL AS DebitoTotal
FROM CAPHOTELCLIENTEQUARTO
JOIN CAPHOTELCLIENTE ON CAPHOTELCLIENTE.SEQCODCLIENTE = CAPHOTELCLIENTEQUARTO.CLIENTE
JOIN CAPHOTELQUARTO ON CAPHOTELQUARTO.SEQCODQUARTO = CAPHOTELCLIENTEQUARTO.TPQUARTOCONTRATADO
WHERE CAPHOTELCLIENTE.SEQCODCLIENTE = 1
