--SELECT utilizado para retornar informações para o RelADOLTUcomplexo
SELECT LTUUSUARIO.SEQLTUUSUARIO AS SEQUSUARIO,
 LTUUSUARIO.NOME AS NomeUsuario,
 LTUUSUARIO.DATA_CRIACAO AS DataUsuario,
 LTUCATALOGOS.NOME AS NomeCatalogo,
 LTUTITULOS.NOME AS NomeTitulo,
 LTUTITULOS.DATA_CRIACAO AS DataTitulo
FROM LTUCATALOGOS
JOIN LTUCATALOGOS_USUARIOS ON LTUCATALOGOS.SEQLTUCATALOGO = LTUCATALOGOS_USUARIOS.CATALOGO
JOIN LTUCATALOGOS_TITULOS ON LTUCATALOGOS.SEQLTUCATALOGO = LTUCATALOGOS_TITULOS.CATALOGO
JOIN LTUTITULOS ON LTUCATALOGOS_TITULOS.TITULO = LTUTITULOS.SEQLTUTITULOS
JOIN LTUUSUARIO ON LTUCATALOGOS_USUARIOS.USUARIO = LTUUSUARIO.SEQLTUUSUARIO
WHERE LTUUSUARIO.DATA_CRIACAO BETWEEN TO_DATE('2024-04-08', 'YYYY-MM-DD') AND TO_DATE('2024-04-09', 'YYYY-MM-DD') AND LTUUSUARIO.SEQLTUUSUARIO = 36

--Retorna o ID e Nome do User
SELECT SEQLTUUSUARIO AS IDUSER, NOME FROM LTUUSUARIO

--Select utilizado para retornar o SEQ récem inserido na tabela, qual é utilizado para fazer insert catalos_titulos
SELECT SEQLTUTITULOS AS IDTITULO FROM LTUTITULOS WHERE SEQLTUTITULOS = (SELECT MAX(SEQLTUTITULOS) FROM LTUTITULOS)

-- Retorna os títulos por catálogo contratado pelo usuário
SELECT LTUTITULOS.NOME AS TITULO, LTUCATALOGOS.SEQLTUCATALOGO, LTUCATALOGOS.NOME AS CATALOGO, LTUUSUARIO.NOME AS USUARIO
FROM LTUCATALOGOS
JOIN LTUCATALOGOS_USUARIOS ON LTUCATALOGOS.SEQLTUCATALOGO = LTUCATALOGOS_USUARIOS.CATALOGO
JOIN LTUCATALOGOS_TITULOS ON LTUCATALOGOS.SEQLTUCATALOGO = LTUCATALOGOS_TITULOS.CATALOGO
JOIN LTUTITULOS ON LTUCATALOGOS_TITULOS.TITULO = LTUTITULOS.SEQLTUTITULOS
JOIN LTUUSUARIO ON LTUCATALOGOS_USUARIOS.USUARIO = LTUUSUARIO.SEQLTUUSUARIO
WHERE LTUCATALOGOS_USUARIOS.USUARIO = 1;

--TABELAS
--Ordem das tabelas LTUCATALOGOS --> LTUTITULOS --> LTUUSUARIO --> LTUCATALOGOS_TITULOS --> LTUCATALOGOS_USUARIOS

--Drop Table LTUCATALOGOS;
DROP SEQUENCE SEQLTUCATALOGO;
DROP TABLE LTUCATALOGOS;

CREATE SEQUENCE SEQLTUCATALOGO MINVALUE 1 START WITH 1 INCREMENT BY 1;
Create Table LTUCATALOGOS(
  SEQLTUCATALOGO Number(22) Not Null,
  NOME Varchar(100)  Null
);
Alter Table LTUCATALOGOS Add Constraint PK_LTUCATALOGOS Primary Key (SEQLTUCATALOGO);

INSERT INTO LTUCATALOGOS (SEQLTUCATALOGO, NOME) VALUES (SEQLTUCATALOGO.NEXTVAL, 'Esporte');
INSERT INTO LTUCATALOGOS (SEQLTUCATALOGO, NOME) VALUES (SEQLTUCATALOGO.NEXTVAL, 'Moda');
INSERT INTO LTUCATALOGOS (SEQLTUCATALOGO, NOME) VALUES (SEQLTUCATALOGO.NEXTVAL, 'Ação');
INSERT INTO LTUCATALOGOS (SEQLTUCATALOGO, NOME) VALUES (SEQLTUCATALOGO.NEXTVAL, 'Aventura');
INSERT INTO LTUCATALOGOS (SEQLTUCATALOGO, NOME) VALUES (SEQLTUCATALOGO.NEXTVAL, 'Comedia');

--Drop Table LTUTITULOS;
DROP SEQUENCE SEQLTUTITULOS;
DROP TABLE LTUTITULOS;

CREATE SEQUENCE SEQLTUTITULOS MINVALUE 1 START WITH 1 INCREMENT BY 1;
Create Table LTUTITULOS(
  SEQLTUTITULOS Number(22) Not Null,
  NOME Varchar(100) Null
);
Alter Table LTUTITULOS Add Constraint PK_LTUTITULOS Primary Key (SEQLTUTITULOS);
ALTER TABLE LTUTITULOS ADD (DATA_CRIACAO DATE DEFAULT SYSDATE);

INSERT INTO LTUTITULOS (SEQLTUTITULOS, NOME, DATA_CRIACAO) VALUES (SEQLTUTITULOS.NEXTVAL, 'Um programador da Pesadona', TO_DATE('06-04-2024', 'DD-MM-YYYY'));
INSERT INTO LTUTITULOS (SEQLTUTITULOS, NOME) VALUES (SEQLTUTITULOS.NEXTVAL, 'Apertem os Cintos, o Programador Sumiu');
INSERT INTO LTUTITULOS (SEQLTUTITULOS, NOME) VALUES (SEQLTUTITULOS.NEXTVAL, 'Teste Título Novo');
INSERT INTO LTUTITULOS (SEQLTUTITULOS, NOME) VALUES (SEQLTUTITULOS.NEXTVAL, 'O maravilhoso mundo dos Bits e Bytes');
INSERT INTO LTUTITULOS (SEQLTUTITULOS, NOME) VALUES (SEQLTUTITULOS.NEXTVAL, 'Charm and Clean Code');

--Drop Table LTUUSUARIO;
DROP SEQUENCE SEQLTUUSUARIO;
DROP TABLE LTUUSUARIO;

CREATE SEQUENCE SEQLTUUSUARIO MINVALUE 1 START WITH 1 INCREMENT BY 1;
Create Table LTUUSUARIO(
  SEQLTUUSUARIO Number(22) Not Null,
  NOME Varchar(100) Null
);
Alter Table LTUUSUARIO Add Constraint PK_LTUUSARIO Primary Key (SEQLTUUSUARIO);
ALTER TABLE LTUUSUARIO ADD (DATA_CRIACAO DATE DEFAULT SYSDATE);

INSERT INTO LTUUSUARIO (SEQLTUUSUARIO, NOME) VALUES (SEQLTUUSUARIO.NEXTVAL, 'AMANDA');
INSERT INTO LTUUSUARIO (SEQLTUUSUARIO, NOME) VALUES (SEQLTUUSUARIO.NEXTVAL, 'BRAYAN');
INSERT INTO LTUUSUARIO (SEQLTUUSUARIO, NOME) VALUES (SEQLTUUSUARIO.NEXTVAL, 'CONTE');
INSERT INTO LTUUSUARIO (SEQLTUUSUARIO, NOME) VALUES (SEQLTUUSUARIO.NEXTVAL, 'EDUARDO');

--Drop Table LTUCATALOGOS_TITULOS;
DROP SEQUENCE SEQLTUCATALOGO_TITULO;
DROP TABLE LTUCATALOGOS_TITULOS;

CREATE SEQUENCE SEQLTUCATALOGO_TITULO MINVALUE 1 START WITH 1 INCREMENT BY 1;
Create Table LTUCATALOGOS_TITULOS(
  SEQLTUCATALOGO_TITULO Number(22) Not Null,
  CATALOGO Number(22) Not Null,
  TITULO Number(22) Not Null
);

Alter Table LTUCATALOGOS_TITULOS Add Constraint PK_LTUCATALOGOS_TITULOS Primary Key (SEQLTUCATALOGO_TITULO);
Alter Table LTUCATALOGOS_TITULOS Add Constraint FK_LTUCAT_TIT_CATALOGOS Foreign Key (CATALOGO) References LTUCATALOGOS (SEQLTUCATALOGO) ON DELETE CASCADE;
Alter Table LTUCATALOGOS_TITULOS Add Constraint FK_LTUCAT_TIT_TITULOS Foreign Key (TITULO) References LTUTITULOS (SEQLTUTITULOS) ON DELETE CASCADE;

INSERT INTO LTUCATALOGOS_TITULOS (SEQLTUCATALOGO_TITULO, CATALOGO, TITULO) VALUES (SEQLTUCATALOGO_TITULO.NEXTVAL, 1, 1);
INSERT INTO LTUCATALOGOS_TITULOS (SEQLTUCATALOGO_TITULO, CATALOGO, TITULO) VALUES (SEQLTUCATALOGO_TITULO.NEXTVAL, 2, 2);
INSERT INTO LTUCATALOGOS_TITULOS (SEQLTUCATALOGO_TITULO, CATALOGO, TITULO) VALUES (SEQLTUCATALOGO_TITULO.NEXTVAL, 3, 3);
INSERT INTO LTUCATALOGOS_TITULOS (SEQLTUCATALOGO_TITULO, CATALOGO, TITULO) VALUES (SEQLTUCATALOGO_TITULO.NEXTVAL, 4, 4);
INSERT INTO LTUCATALOGOS_TITULOS (SEQLTUCATALOGO_TITULO, CATALOGO, TITULO) VALUES (SEQLTUCATALOGO_TITULO.NEXTVAL, 5, 5);
INSERT INTO LTUCATALOGOS_TITULOS (SEQLTUCATALOGO_TITULO, CATALOGO, TITULO) VALUES (SEQLTUCATALOGO_TITULO.NEXTVAL, 4, 2);


--Drop Table LTUCATALOGOS_USUARIOS;
DROP SEQUENCE SEQLTUCATALOGO_USUARIO;
DROP TABLE LTUCATALOGOS_USUARIOS;

CREATE SEQUENCE SEQLTUCATALOGO_USUARIO MINVALUE 1 START WITH 1 INCREMENT BY 1;
Create Table LTUCATALOGOS_USUARIOS(
  SEQLTUCATALOGO_USUARIO Number(22) Not Null,
  CATALOGO Number(22) Not Null,
  USUARIO Number(22) Not Null
);
Alter Table LTUCATALOGOS_USUARIOS Add Constraint PK_LTUCATALOGOS_USUARIOS Primary Key (SEQLTUCATALOGO_USUARIO);
Alter Table LTUCATALOGOS_USUARIOS Add Constraint FK_LTUCAT_USU_CATALOGOS Foreign Key (CATALOGO) References LTUCATALOGOS (SEQLTUCATALOGO) ON DELETE CASCADE;
Alter Table LTUCATALOGOS_USUARIOS Add Constraint FK_LTUCAT_USU_USUARIOS Foreign Key (USUARIO) References LTUUSUARIO (SEQLTUUSUARIO) ON DELETE CASCADE;

INSERT INTO LTUCATALOGOS_USUARIOS (SEQLTUCATALOGO_USUARIO, CATALOGO, USUARIO) VALUES (SEQLTUCATALOGO_USUARIO.NEXTVAL, 2, 1);
INSERT INTO LTUCATALOGOS_USUARIOS (SEQLTUCATALOGO_USUARIO, CATALOGO, USUARIO) VALUES (SEQLTUCATALOGO_USUARIO.NEXTVAL, 3, 2);
INSERT INTO LTUCATALOGOS_USUARIOS (SEQLTUCATALOGO_USUARIO, CATALOGO, USUARIO) VALUES (SEQLTUCATALOGO_USUARIO.NEXTVAL, 5, 3);
INSERT INTO LTUCATALOGOS_USUARIOS (SEQLTUCATALOGO_USUARIO, CATALOGO, USUARIO) VALUES (SEQLTUCATALOGO_USUARIO.NEXTVAL, 1, 4);
INSERT INTO LTUCATALOGOS_USUARIOS (SEQLTUCATALOGO_USUARIO, CATALOGO, USUARIO) VALUES (SEQLTUCATALOGO_USUARIO.NEXTVAL, 1, 2);